# Generated by Django 5.1.3 on 2025-01-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_options_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
