# Generated by Django 5.1.3 on 2025-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_profile_bio_profile_country_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='pf_pics/default.png', upload_to=''),
        ),
    ]
