# Generated by Django 5.1.3 on 2025-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_postimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
    ]
