# Generated by Django 5.1.3 on 2025-02-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_post_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='other', max_length=50),
        ),
    ]
